#ifndef RAPTOR_CONFIG_HPP
#define RAPTOR_CONFIG_HPP

#define ASSET_DIRECTORY "../../resources/assets/"
#define SHADER_DIRECTORY "../../resources/shaders/"

#define ENABLE_ASSET_RELOADING

#define PROFILER_ENABLED
#define PROFILER_PERSISTANT_SAMPLE_COUNT 64

#define GENERATE_SHADER_SOURCE_FILES
#define GENERATE_SHADER_SOURCE_FILE_DIRECTORY "generated_shaders/"

#define MATERIAL_NAME_MAX_SIZE 64

#define FORCE_SINGLE_THREADED false
#define FORCE_MINIMUM_THREAD_COUNT 2

#endif // RAPTOR_CONFIG_HPP