# SDL2_MIXER_INCLUDE_DIR  = where SDL_mixer.h can be found
# SDL2_MIXER_LIBRARY      = the library to link against SDL2_mixer
# SDL2_MIXER_FOUND        = set to 1 if SDL2_mixer is found

if(SDL2_MIXER_INCLUDE_DIRS)
  find_path(SDL2_MIXER_INCLUDE_DIR SDL2/SDL_mixer.h ${SDL2_Mixer_INCLUDE_DIRS})
  find_library(SDL2_MIXER_LIBRARY SDL2_mixer ${SDL2_Mixer_LIBRARY_DIRS})
else(SDL2_MIXER_INCLUDE_DIRS)
set(TRIAL_LIBRARY_PATHS
  $ENV{SDL2_MIXER_HOME}/lib
  /usr/lib
  /usr/local/lib
  /sw/lib
)
set(TRIAL_INCLUDE_PATHS
  $ENV{SDL2_MIXER_HOME}/include/SDL2
  /usr/include/SDL2
  /usr/local/include/SDL2
  /sw/include/SDL2
)
find_library(SDL2_MIXER_LIBRARY SDL2_mixer ${TRIAL_LIBRARY_PATHS})
find_path(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h ${TRIAL_INCLUDE_PATHS})

endif(SDL2_MIXER_INCLUDE_DIRS)

IF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 1 CACHE BOOL "Found SDL2_Mixer library")
ELSE(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
  SET(SDL2_MIXER_FOUND 0 CACHE BOOL "Not fount SDL2_Mixer library")
ENDIF(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)

MARK_AS_ADVANCED(
  SDL2_MIXER_INCLUDE_DIR
  SDL2_MIXER_LIBRARY
  SDL2_MIXER_FOUND
)
